# Generated by Django 3.2.20 on 2023-09-21 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('house_no', models.CharField(max_length=256)),
                ('street', models.CharField(max_length=556)),
                ('city', models.CharField(max_length=256)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(blank=True, max_length=1256, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='proteindata/static/profilePics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteindata.address')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('category_description', models.CharField(max_length=1056)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=256)),
                ('tool_description', models.CharField(max_length=1056)),
                ('tool_photo', models.ImageField(blank=True, null=True, upload_to='proteindata/static/toolPics/')),
                ('tool_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteindata.category')),
                ('tool_location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteindata.address')),
                ('tool_owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteindata.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRequests',
            fields=[
                ('request_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('acceptance_status', models.BooleanField(blank=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteindata.appuser')),
                ('tool_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proteindata.tool')),
            ],
        ),
    ]
